site:
  title: FreeRADIUS documentation
  url: https://www.freeradius.org/docs
content:
  sources:
  - url: https://github.com/FreeRADIUS/freeradius-server.git
    branches: master
    start_path: doc/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
